name: Script Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        function:
          - test_install_packages
          - test_modify_php_ini
          - test_setup_webroot
          - test_setup_apache
          - test_setup_mysql
          - test_setup_cronjobs

    steps:
    - uses: actions/checkout@v2

    - name: Make script executable
      run: chmod +x ./i.sh

    - name: Run test function
      run: |
        sudo bash ./i.sh --test-function ${{ matrix.function }} --domain example.com
        
  full-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run full test mode
      run: |
        sudo bash ./i.sh --test --domain example.com