name: Script Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        function:
          - check_version
          - verify_script
          - check_root
          - check_os
          - get_domain
          - generate_passwords
          - install_packages
          - modify_php_ini
          - setup_webroot
          - setup_apache
          - clone_nestogy
          - setup_cronjobs
          - generate_cronkey_file
          - setup_mysql

    steps:
    - uses: actions/checkout@v4

    - name: Make script executable
      run: chmod +x ./i.sh

    - name: Run test function
      run: |
        sudo bash ./i.sh --test-function ${{ matrix.function }} --domain example.com
        
  full-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run full test mode
      run: |
        sudo bash ./i.sh --test --domain example.com