name: Update Script Checksum

on:
  push:
    paths:
      - 'itflow_install.sh'
    branches:
      - main

jobs:
  update-checksum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate SHA256
        run: |
          sha256sum itflow_install.sh | awk '{print $1}' > itflow_install.sh.sha256

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add itflow_install.sh.sha256
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update SHA256 checksum" && git push) 